
services:
  patient-service-db:
    build:
      context: ./patient-service
      dockerfile: Dockerfile.patient-service-db
    image: pm/patient-service-db:v1
    container_name: patient_service_db
    restart: always
    env_file:
      - ./patient-service/.env
    ports:
      - 5000:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pm

  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile.patient-service
    image: pm/patient-service:v1
    container_name: patient_service_app
    restart: always
    depends_on:
      - patient-service-db
      - kafka
    env_file:
      - ./patient-service/.env
    ports:
      - 4000:4000
    networks:
      - pm

  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile.billing-service
    image: pm/billing-service:v1
    container_name: billing_service_app
    restart: always
    depends_on:
      - kafka
    ports:
      - 4001:4001
      - 9001:9001
    networks:
      - pm

  kafka:
    build:
      context: .
      dockerfile: Dockerfile.kafka
    image: pm/kafka:v1
    container_name: kafka
    restart: always
    # depends_on:
    #   - patient-service-db
    env_file:
      - .env
    ports:
      - 9092:9092
      - 9093:9093
      - 9094:9094
    networks:
      - pm

  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile.analytics-service
    image: pm/analytics-service
    container_name: analytics_service_app
    restart: always
    depends_on:
    - kafka
    env_file:
      - ./analytics-service/.env
    ports:
      - 4002:4002
    networks:
      - pm



volumes:
  postgres_data:

networks:
  pm: