spring:
  application:
    name: API Gateway
  cloud:
    gateway:
      routes:
        - id: patient-service-routes
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
          # REST CLIENT -> http://localhost:4004/api/patients
          # api gateway uses this rules to route req
          # API GATEWAY -> http://patient-service:4000/patients  /api is stripped
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients, /v3/api-docs
  
server:
  port: 4004